In [ ]:
import pandas as pd

df =pd.read_parquet("data.parquet")

,a_quitte_l_entreprise,nombre_participation_pee,nb_formations_suivies,distance_domicile_travail,niveau_education,domaine_etude,frequence_deplacement,annees_depuis_la_derniere_promotion,annes_sous_responsable_actuel,age,...,satisfaction_employee_environnement,note_evaluation_precedente,niveau_hierarchique_poste,satisfaction_employee_nature_travail,satisfaction_employee_equipe,satisfaction_employee_equilibre_pro_perso,note_evaluation_actuelle,heure_supplementaires,augementation_salaire_precedente_percent,est_un_homme
0,True,0,0,1,2,Infra & Cloud,1,0,5,41,...,2,3,2,4,1,1,3,True,11,False
1,False,1,3,8,1,Infra & Cloud,2,1,7,49,...,3,2,2,2,4,3,4,False,23,True
2,True,0,3,2,2,Autre,1,0,0,37,...,4,2,1,3,2,3,3,True,15,True
3,False,0,3,3,4,Infra & Cloud,2,3,0,33,...,4,3,1,3,3,3,3,True,11,False
4,False,1,3,2,1,Transformation Digitale,1,2,2,27,...,1,3,1,2,4,3,3,False,12,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,False,1,3,23,2,Transformation Digitale,2,0,3,36,...,3,4,2,4,3,3,3,False,17,True
1466,False,1,5,6,1,Transformation Digitale,1,1,7,39,...,4,2,3,1,1,3,3,False,15,True
1467,False,1,0,4,3,Infra & Cloud,1,0,3,27,...,2,4,2,2,2,3,4,True,20,True
1468,False,0,3,2,3,Transformation Digitale,2,0,8,49,...,4,2,2,2,4,2,3,False,14,True
1469,False,0,3,8,3,Transformation Digitale,1,1,2,34,...,2,4,2,3,1,4,3,False,12,True

## Conversion des types

In [20]:
# domaine_etude => qualitative nominale
# get_dummies drop automatiquement ["domaine_etude"]
# drop_first = Supprime la 1er catégorie (Célibataire) pour éviter la multicolinéarité, elle devient implicite si toutes les autres catégories sont à 0
df = pd.get_dummies(df, columns=["domaine_etude"], drop_first=True)

In [21]:
# statut_marital => qualitative nominale
# get_dummies drop automatiquement ["statut_marital"]
# drop_first = Supprime la 1er catégorie (Célibataire) pour éviter la multicolinéarité, elle devient implicite si toutes les autres catégories sont à 0
df = pd.get_dummies(df, columns=["statut_marital"], drop_first=True)

In [22]:
# departement => qualitative nominale
# get_dummies drop automatiquement ["departement"]
# drop_first = Supprime la 1er catégorie (Commercial) pour éviter la multicolinéarité, elle devient implicite si toutes les autres catégories sont à 0
df = pd.get_dummies(df, columns=["departement"], drop_first=True)

In [23]:
# poste => qualitative nominale
# get_dummies drop automatiquement ["poste"]
# drop_first = Supprime la 1er catégorie (Assistant) pour éviter la multicolinéarité, elle devient implicite si toutes les autres catégories sont à 0
df = pd.get_dummies(df, columns=["poste"], drop_first=True)

In [28]:
pd.DataFrame({
    "colonne": df.columns,
    "type": df.dtypes.values
})

                                      colonne   type
0                       a_quitte_l_entreprise   bool
1                    nombre_participation_pee  int64
2                       nb_formations_suivies  int64
3                   distance_domicile_travail  int64
4                            niveau_education  int64
5                       frequence_deplacement  int64
6         annees_depuis_la_derniere_promotion  int64
7               annes_sous_responsable_actuel  int64
8                                         age  int64
9                              revenu_mensuel  int64
10             nombre_experiences_precedentes  int64
11                    annee_experience_totale  int64
12                   annees_dans_l_entreprise  int64
13                annees_dans_le_poste_actuel  int64
14        satisfaction_employee_environnement  int64
15                 note_evaluation_precedente  int64
16                  niveau_hierarchique_poste  int64
17       satisfaction_employee_nature_travail  int64
18               satisfaction_employee_equipe  int64
19  satisfaction_employee_equilibre_pro_perso  int64
20                   note_evaluation_actuelle  int64
21                      heure_supplementaires   bool
22   augementation_salaire_precedente_percent  int64
23                               est_un_homme   bool
24              domaine_etude_Entrepreunariat   bool
25                domaine_etude_Infra & Cloud   bool
26                    domaine_etude_Marketing   bool
27          domaine_etude_Ressources Humaines   bool
28      domaine_etude_Transformation Digitale   bool
29                  statut_marital_Divorcé(e)   bool
30                    statut_marital_Marié(e)   bool
31                     departement_Consulting   bool
32            departement_Ressources Humaines   bool
33                     poste_Cadre Commercial   bool
34                           poste_Consultant   bool
35                  poste_Directeur Technique   bool
36                              poste_Manager   bool
37              poste_Représentant Commercial   bool
38                  poste_Ressources Humaines   bool
39                       poste_Senior Manager   bool
40                            poste_Tech Lead   bool

# séparation train/test

In [24]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['a_quitte_l_entreprise'])
y = df['a_quitte_l_entreprise']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
print(f"Taille du jeu d'entraînement : {X_train.shape[0]} lignes")
print(f"Taille du jeu de test : {X_test.shape[0]} lignes")

Taille du jeu d'entraînement : 1176 lignes
Taille du jeu de test : 294 lignes

# choix de l’algorithme (régression, classification, clustering…)

# entraînement du modèle

# optimisation des hyperparamètres

# validation croisée

# évaluation des performances (accuracy, RMSE, F1, etc.)

# Résultat

# Prédictions sur de nouvelles données

# Export

In [27]:
df.to_parquet("model.parquet")